In [47]:
import numpy as np


In [2]:
z1=np.array([1,3,5,7,9])
z2=z1+1

In [3]:
z1

array([1, 3, 5, 7, 9])

In [4]:
z2

array([ 2,  4,  6,  8, 10])

In [6]:
ind=[0,2,3]
z1[ind]

array([1, 5, 7])

In [7]:
ind=np.array([0,2,3])
z1[ind]

array([1, 5, 7])

In [9]:
#boolean array or logical array
z1>6

array([False, False, False,  True,  True])

In [10]:
#using logical index vector to return just elements of certain condition
z1[z1>6]

array([7, 9])

In [11]:
z2[z1>6]

array([ 8, 10])

In [12]:
ind=z1>6

In [13]:
z1[ind]

array([7, 9])

In [14]:
#when u slice an array, a view of it is returned. it will be mutable
#when u index an array a copy of it is returned which is immutable
z1=np.array([1,3,5,7,9])
w=z1[0:3]
w

array([1, 3, 5])

In [18]:
w=z1[0:3]
w[0]=3

In [19]:
w

array([3, 3, 5])

In [20]:
z1

array([3, 3, 5, 7, 9])

In [21]:
z1=np.array([1,3,5,7,9])
ind=np.array([0,1,2])
ind

array([0, 1, 2])

In [23]:
w=z1[ind]
w

array([1, 3, 5])

In [24]:
w[0]=3

In [25]:
w

array([3, 3, 5])

In [26]:
z1

array([1, 3, 5, 7, 9])

In [27]:
a = np.array([1,2])
b = np.array([3,4,5])
b[a]

array([4, 5])

In [28]:
c = b[1:]
b[a] is c

False

In [48]:
#To construct an array of 10 linearly spaced elements starting with 0
#and ending with 100, we can use the NumPy linspace function.
#syntax ix (starting point, ending point,n0. of elements)
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [46]:
#to construct an average of 10 logarithmically spaced elements
#between 10 and 100, we can do the following.
#syntax ix (log of starting point, log of ending point,n0. of elements)
np.logspace(1,2,10)


[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
hi


In [49]:
np.logspace(np.log10(250),np.log10(500),10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

In [50]:
X=np.array([[1,2,3],[4,5,6]])

In [51]:
#Finding the shape of an array
X.shape

(2, 3)

In [52]:
#to check the no if elements in the array
#there is no parenthesis when calling shape or size cos they are attributes not functions
X.size

6

In [53]:
x=np.random.random(10)


In [54]:
np.any(x>0.9)

True

In [57]:
np.all(x>=.1)

True

In [56]:
x

array([0.47144418, 0.33579343, 0.942165  , 0.98268616, 0.49657628,
       0.36945467, 0.8436579 , 0.43541754, 0.16055555, 0.18453505])

In [58]:
#Checking orime numbers
x = 20
not np.any([x%i == 0 for i in range(2, x)])

False