In [1]:
import numpy as np


In [2]:
z1=np.array([1,3,5,7,9])
z2=z1+1

In [3]:
z1

array([1, 3, 5, 7, 9])

In [4]:
z2

array([ 2,  4,  6,  8, 10])

In [6]:
ind=[0,2,3]
z1[ind]

array([1, 5, 7])

In [7]:
ind=np.array([0,2,3])
z1[ind]

array([1, 5, 7])

In [9]:
#boolean array or logical array
z1>6

array([False, False, False,  True,  True])

In [10]:
#using logical index vector to return just elements of certain condition
z1[z1>6]

array([7, 9])

In [11]:
z2[z1>6]

array([ 8, 10])

In [12]:
ind=z1>6

In [13]:
z1[ind]

array([7, 9])

In [14]:
#when u slice an array, a view of it is returned. it will be mutable
#when u index an array a copy of it is returned which is immutable
z1=np.array([1,3,5,7,9])
w=z1[0:3]
w

array([1, 3, 5])

In [18]:
w=z1[0:3]
w[0]=3

In [19]:
w

array([3, 3, 5])

In [20]:
z1

array([3, 3, 5, 7, 9])

In [21]:
z1=np.array([1,3,5,7,9])
ind=np.array([0,1,2])
ind

array([0, 1, 2])

In [23]:
w=z1[ind]
w

array([1, 3, 5])

In [24]:
w[0]=3

In [25]:
w

array([3, 3, 5])

In [26]:
z1

array([1, 3, 5, 7, 9])

In [27]:
a = np.array([1,2])
b = np.array([3,4,5])
b[a]

array([4, 5])

In [28]:
c = b[1:]
b[a] is c

False

In [29]:
#To construct an array of 10 linearly spaced elements starting with 0
and ending with 100, we can use the NumPy linspace function.
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
print(np.logspace(1,2,10))