In [1]:
#NumPy arrays are an additional data type provided by NumPy, and they are used for representing vectors and matrices.
#NumPy arrays have a size that is fixed when they are constructed.
#Elements of NumPy arrays are also all of the same data
#By default the elements are floating numbers


In [6]:
import numpy as np

zero_vector=np.zeros(5)

#for this, we define the rows and columns
zero_matrix=np.zeros((5,3))

In [3]:
zero_vector

array([0., 0., 0., 0., 0.])

In [7]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
####### we assume that lower case variables
#are vectors or one-dimensional arrays and upper case variables are
#matrices, or two-dimensional arrays.

In [11]:
x=np.array([1,2,3])
y=np.array([2,4,6])

In [12]:
z=np.array([[1,3],[5,9]])

In [13]:
z

array([[1, 3],
       [5, 9]])

In [14]:
#Transposinng a matrix thus first column becomes first row and first row becomes forst column
z.transpose()

array([[1, 5],
       [3, 9]])

In [16]:
### SLCING ARRAYS
x=np.array([1,2,3])
y=np.array([2,4,6])
X=np.array([[1,2,3],[4,5,6]])
Y=np.array([[2,4,6],[8,10,12]])

In [17]:
x[2]

3

In [18]:
x[0:2]

array([1, 2])

In [19]:
z=x+y

In [20]:
z

array([3, 6, 9])

In [21]:
#this returns first column of X
X[:,1]

array([2, 5])

In [22]:
Y[:,1]

array([ 4, 10])

In [23]:
X[:,1]+Y[:,1]

array([ 6, 15])

In [24]:
#To extract the first column of y
Y[1,:]

array([ 8, 10, 12])

In [25]:
#To extract first row of X
X[1]

array([4, 5, 6])

In [26]:
[2,4]+[6,8]

[2, 4, 6, 8]

In [27]:
np.array([2,4])+np.array([6,8])

array([ 8, 12])

In [28]:
x = np.array([1,2,5])
x[1:2]

array([2])

In [29]:
a = np.array([1,2])
b = np.array([3,4,5])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 